name: Only Recipes
options:
  xcodeVersion: 15.3
  minimumXcodeGenVersion: 2.39.0
  createIntermediateGroups: true
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "17.0"
targets:
  Only Recipes:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [Only Recipes]
    info:
      path: Only Recipes/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.humblebots.only-recipes

settings:
  GENERATE_INFOPLIST_FILE: NO
  CODE_SIGNING_ALLOWED: NO
  MARKETING_VERSION: 1.0.0
  base:
    CURRENT_PROJECT_VERSION: 1
# ############
# # fileGroups
# ############

# # fileGroups:
# #   - config

# ############
# # Packages
# ############

# # packages:
# # SwiftyUtils:
# #   url: https://github.com/tbaranes/SwiftyUtils
# #   from: 5.0.0

# ############
# # Settings
# ############

# # settings:
# #   PRODUCT_BUNDLE_IDENTIFIER: $(AS_BUNDLE_IDENTIFIER)

# targets:
#   MyApp:
#     type: application
#     supportedDestinations: [iOS]
#     deploymentTarget:
#       iOS: 17.0
#     sources:
#       - path: MyApp
#         inferDestinationFiltersByPath: true
#       - path: OtherSources
#         destinationFilters: [iOS]
